# Generated by Django 2.1.2 on 2018-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monelecteur',
            name='numero_electeur',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
